name: Build

on:
  push:
    branches:
        - '*'
  pull_request:
    branches:
        - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Download Everest lib-stripped
      uses: robinraju/release-downloader@v1.4
      with:
        repository: EverestAPI/Everest
        latest: true
        fileName: lib-stripped.zip

    - name: Extract lib-stripped.zip
      run: unzip lib-stripped.zip

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build Source/SorbetHelper.csproj --configuration Release --no-restore
      env:
        CelestePrefix: ${{ github.workspace }}/lib-stripped

    - name: Upload Artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        name: SorbetHelper
        path: |
          everest.yaml
          bin/SorbetHelper.dll
          bin/SorbetHelper.pdb
          Ahorn/**/*
          Audio/**/*
          Dialog/**/*
          Graphics/**/*
          Loenn/**/*
          Effects/**/*.cso
